version: '3'
services:
  safra-education:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - database
  database:
    image: mysql:8.0.21
    environment:
      - MYSQL_ROOT_PASSWORD=foobar
      - MYSQL_USER=sbdb
      - MYSQL_PASSWORD=foobar
      - MYSQL_DATABASE=safraeducationdb   
    ports:
      - "3306:3306"